# Generated by Django 5.2.1 on 2025-05-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
