# Generated by Django 5.2.1 on 2025-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_presente_cor_destaque_presente_cor_fundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presente',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status da Aprovação'),
        ),
    ]
